### PR TITLE
Improve the README + add more stuff

### PR DESCRIPTION
**Pull request by ajhalili2006**
## TO-DO
* [X] better README than https://github.com/intellivoid/SpamProtectionAgent/commit/686dd0b191364a97754e505ed61beed19a621442
* [X] security policy for maintainers and security experts to follow when reporting security issues
* [X] Example `config.py` file
* [ ] Issue and PR templates

### CODE REVIEW

**Review by takarushi — COMMENTED** [review]
security@intellivoid.net doesn't exists right now, also there's a lot of typos that need to be fixed, please commit the requested changes to your repo, close the actual PR and open a new one with the changes done

**Review by takarushi — COMMENTED** [review]
Again, another typos on this one, you may also want to removd the dot and the end of the filename so github will pick it up correctly

**Comment by takarushi** [comment]
Ok, for now, that's all the potential errors that i can see on this PR, i would recommend you to check this code reviews and add the proposed changes.

**Comment by ajhalili2006** [comment]
> Ok, for now, that's all the potential errors that i can see on this PR, i would recommend you to check this code reviews and add the proposed changes.

Hi @takarushi,

Can you please point out what files and lines are having issues that maintainers blocked this MR from being
merged to the `clients` branch? Thanks.

**Review by Netkas — APPROVED** [review]

**Pull request merged**
